elearning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('',include(('subcourse.urls','subcourse'),namespace='subcourse')),
    path('user/',include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',Main,name='main'),
    path('my/',HomeView.as_view(),name='homey'),
    path('my/course-<int:pk>',DetailCourse.as_view(),name='courses_page'),
    path('my/course-<int:id>/attendance-<int:pk>',DetailAttend.as_view(),name='detail_attend'),
    path('add-course/',AddCourse.as_view(template_name='main/add_course.html'),name='add_course'),
    path('remove-attendance/<int:pk>',RmvAttendance.as_view(),name="remove-attendance")
]

subcourse/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


name_app = 'subcourse'
urlpatterns = [
    path('my/section-<int:pk>-edit',SectionEdit.as_view(),name='section_edit'),
    path('my/course-<int:id>/sbcs/<slug:slug>',SubCourseView.as_view(),name='sub_course'),
    path('my/course-<int:id>/asgt/<slug:slug>',DetailAssignment.as_view(),name='assignment'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.utils.text import slugify
from django.utils import timezone

# User
class CustomUser(AbstractUser):
    TYPE_CHOICES = (
        ('Std', 'Student'),
        ('Tcr', 'Teacher'),
        ('Adm', 'Admin'),
    )
    user_type = models.CharField(choices=TYPE_CHOICES,default='Std',max_length=3)

# <<<=====================================================================>>>
class Teacher(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    description = models.CharField(max_length=255,null=True, blank=True)

    def __str__(self):
        return self.user.username

class Classroom(models.Model):
    name = models.CharField(max_length=155)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Student(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    class_id = models.ForeignKey(Classroom,on_delete=models.SET_NULL,null=True,blank=True)
    
    def __str__(self):
        return self.user.username

class Course(models.Model):
    name = models.CharField(max_length=255,null=True)
    teacher_id = models.ForeignKey(Teacher,on_delete=models.SET_NULL,null=True,blank=True)
    class_id = models.ForeignKey(Classroom,on_delete=models.SET_NULL,null=True,blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} Kelas {self.class_id.name}'

    def get_absolute_url(self):
        return '/'

# class SubCourseFile(models.Model):
#     subcourse_id = models.ForeignKey(SubCourse,on_delete=models.CASCADE,null=True)
#     file = models.FileField(upload_to="uploads_file/")


class AttendanceReq(models.Model):
    course_id = models.ForeignKey(Course,on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    closed_time = models.DateTimeField()
    is_closed = models.BooleanField(default=False)

    @property
    def check_time(self):
        start = self.start_time
        closed = self.closed_time
        is_closed = self.is_closed
        noww = timezone.now()
        if is_closed:
            if noww.date() == start.date():
                if noww.time() >= start.time():
                    self.is_closed = True



    def __str__(self):
        return f'{self.course_id} Tanggal {self.date_time.date()} Closed = {self.is_closed}'

    def get_absolute_url(self):
        return f'/my/course-{self.course_id}'

    

class Attendance(models.Model):
    ATTENDANCE_CHOICES = (
        ('absent','Absent'),
        ('present','Present'),
    )
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    attendanceReq_id = models.ForeignKey(AttendanceReq,on_delete=models.CASCADE)
    date_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=ATTENDANCE_CHOICES,max_length=10,default='present')

    def __str__(self):
        return f'{self.student} {self.status} in {self.date_time.time().strftime("%H:%M:%S")}'

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models
from django.contrib.admin.widgets import AdminSplitDateTime


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = models.CustomUser
        fields = '__all__'

class AddNewCourse(forms.ModelForm):
    class Meta:
        model = models.Course
        fields = ['name','teacher_id','class_id']

class AddAttendanceReq(forms.ModelForm):
    start_time = forms.SplitDateTimeField(widget=forms.DateTimeInput(attrs={'class':'date-time'}))
    closed_time = forms.SplitDateTimeField(widget=forms.DateTimeInput(attrs={'class':'date-time'}))
    class Meta:
        model = models.AttendanceReq
        fields = ['is_closed']

class MakeAbsent(forms.ModelForm):
    class Meta:
        model = models.Attendance
        fields = ['status']
        widgets = {'status':forms.RadioSelect}

subcourse/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models
from django.contrib.admin.widgets import AdminSplitDateTime,AdminTimeWidget


class AddSubCourse(forms.ModelForm):
    class Meta:
        model = models.SubCourse
        exclude = ['slug']

class AddSection(forms.ModelForm):
    class Meta:
        model = models.SubSection
        fields = ['title']        

class FormAssignmentTcr(forms.ModelForm):
    start_time = forms.SplitDateTimeField(widget=forms.DateTimeInput(attrs={'class':'date-time'}))
    closed_time = forms.SplitDateTimeField(widget=forms.DateTimeInput(attrs={'class':'date-time'}))
    class Meta:
        model = models.Assignment
        exclude = ["slug"]

main/views.py
from django.shortcuts import redirect, render
from .models import *
from django.core import serializers
from django.contrib.auth.decorators import login_required
from . import forms
from django.urls import reverse,reverse_lazy
from django.views.generic import *
from . import utils
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound,Http404,JsonResponse
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import ModelFormMixin
from subcourse import forms as subforms
from subcourse import models as submodels

# Create your views here.
def Main(request):
    model = Student.objects.all()
    utils.check_expd_absent("all")
    context = {
        'student':model
    }
    return render(request,'main/main.html',context)


class HomeView(LoginRequiredMixin,TemplateView):# this view for homey
    model = Classroom
    
    def get_context_data(self,*args,**kwargs):
        request = self.request
        context =  super().get_context_data(**kwargs) 
        user = request.user
        if user.is_authenticated:
            if user.user_type == 'Std':
                context.update(utils.Context_Std(user))

            elif user.user_type == 'Tcr':
                context.update(utils.Context_Tcr(user))
                context['tcr_or_not'] = 'hola'

        self.template_name = 'main/home.html'
        return context

class DetailCourse(LoginRequiredMixin,SingleObjectMixin,View):# this view for courses_page
    template_name = 'main/detail_crse.html'
    model = Course
    form1 = forms.AddAttendanceReq
    form2 = subforms.AddSection
    form3 = subforms.AddSubCourse
    form4 = subforms.FormAssignmentTcr

    def post(self,request,**kwargs):
        if request.user.user_type == 'Tcr':
            post = request.POST
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                if post['form-type'] == "2":
                    return utils.editSubsection(post,**{"kwargs":kwargs,"form":self.form2})
                elif post['form-type'] == "3":
                    return utils.ajaxPost(post,**{"kwargs":kwargs,"form":self.form3})
                elif post['form-type'] == "4":
                    return utils.ajaxPost(post,**{"kwargs":kwargs,"form":self.form4})
                else:
                    print('lah??')

            else:
                object = self.get_object()
                form = self.form1(post)
                form2 = self.form2(post)
                if form.is_valid():
                    print('hey')
                    start = form.cleaned_data['start_time']
                    closed = form.cleaned_data['closed_time']
                    is_closed = form.cleaned_data['is_closed']
                    att_req = AttendanceReq.objects.create(course_id=object,start_time=start,closed_time=closed,is_closed=is_closed)
                    att_req.save()
                if form2.is_valid():
                    title = form2.cleaned_data['title']
                    section = submodels.SubSection.objects.create(course_id=object,title=title)
                    section.save()
                return redirect('courses_page',object.pk)

    def get(self,request,**kwargs):
        context = {}
        user = request.user
        object = self.get_object()
        context['course'] = object
        returnee = {'object':object,}
        utils.check_expd_absent(object)
        if user.is_authenticated:
            if user.user_type == 'Std':
                context.update(utils.Context_Std(user,**returnee))
                if object.class_id == context['classroom']:
                    return render(request,self.template_name,context)
                else:
                    raise Http404

            elif user.user_type == 'Tcr' :
                context['form1'] = self.form1
                context['form2'] = self.form2
                context['form3'] = self.form3
                context['form4'] = self.form4
                context.update(utils.Context_Tcr(user,**returnee))
                context['tcr_true'] = True
                if object.teacher_id == context['teacher']:
                    return render(request,self.template_name,context)
                else:
                    raise Http404

            else:
                raise Http404
        
class DetailAttend(LoginRequiredMixin,SingleObjectMixin,View):# this view for detail_attend
    model = AttendanceReq
    template_name = 'main/det_attend.html'
    form1 = forms.MakeAbsent


    def post(self,request,**kwargs):
        if request.user.user_type == 'Std':
            form = self.form1(request.POST)
            if form.is_valid():
                student = Student.objects.get(user=request.user)
                attreq_id = AttendanceReq.objects.get(id=kwargs['pk'])
                utils.make_attendance(student,attreq_id,form.cleaned_data['status'])
            return redirect('courses_page', kwargs['id'])

    def get(self,request,**kwargs):
        object = self.get_object()
        context = {}
        user = request.user
        if user.is_authenticated:
            context['object'] = object
            if user.user_type == 'Std':
                context.update(utils.check_no_double_attend(object,request))
            
            elif user.user_type == 'Tcr':
                list_attendance = Attendance.objects.filter(attendanceReq_id=object)
                context['list_attend'] = list_attendance
                context['tcr_true'] = True
            return render(request,self.template_name,context)
        else:
            raise Http404


        
        
# ==========================================<<<<>>>>==================================================

class AddCourse(LoginRequiredMixin,CreateView):
    model = Course
    form_class = forms.AddNewCourse
    succes_url = '/'

    def form_valid(self, form):
        user = self.request.user
        teacher = Teacher.objects.get(user=user)
        form.instance.teacher_id = teacher
        # mengisi bagian teacher_id secara otomatis
        return super().form_valid(form)


class RmvAttendance(LoginRequiredMixin,DeleteView):
    model = AttendanceReq
    success_url = "/my/course-"
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        usr = self.request.user
        tcr = Teacher.objects.get(user=usr)
        course = Course.objects.get(id=self.object.course_id.id)
        success_url = self.get_success_url() + str(course.id)
        if course.teacher_id == tcr:
            self.object.delete()
            return redirect(success_url)
        else:
            raise Http404

subcourse/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.urls import reverse,reverse_lazy
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseNotFound,Http404
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import ModelFormMixin
from main import views as mainview
from main import models as main
from . import models,forms

# Create your views here.

class SubCourseView(LoginRequiredMixin,DetailView):
    template_name = 'subcourse/subcourse.html'
    model = models.SubCourse

class SectionEdit(LoginRequiredMixin,View,SingleObjectMixin):
    template_name = 'subcourse/section_edit.html'
    model = models.SubSection
    form1 = forms.AddSection
    form2 = forms.AddSubCourse
    
    def post(self,request,**kwargs):
        obj = self.get_object()
        if request.user.user_type == 'Tcr':
            form1 = self.form1(request.POST,instance=obj)#needs instance for edit object
            form2 = self.form2(request.POST)
            print('hmmm')
            if form1.is_valid():
                form1.save()
            if form2.is_valid():
                crs_id      = obj.course_id
                sect_id     = obj
                name        = form2.cleaned_data['name']
                content1    = form2.cleaned_data['content1']
                content2    = form2.cleaned_data['content2']
                sub_crs     = models.SubCourse.objects.create(course_id=crs_id,subsection_id=sect_id,
                    name=name,content1=content1,content2=content2
                )
                print(sub_crs)
                sub_crs.save()
            return redirect('courses_page', obj.course_id.pk)

        else:
            raise Http404
        
    def get(self,request,**kwargs):
        self.object = self.get_object()
        self.extra_context = {'form1':self.form1(instance=self.object),'form2':self.form2}
        context = self.get_context_data()
        if request.user.user_type == 'Tcr' or request.user.user_type == 'Adm':# if user is admin or user is a teacher
            return render(request,self.template_name,context)
        else:# if user is a student
            raise Http404


class DetailAssignment(LoginRequiredMixin,DetailView):
    model = models.Assignment
    template_name = 'subcourse/subcourse.html'

templates/main/add_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=`, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    #myDIV {
    padding: 5px 5px;
    }

</style>
<body>
    <p>{{user}}</p>

    <button onclick="myFunction()">Add New Course</button>
    <div id="myDIV">
        <form method="post">
            {% csrf_token %}
            <label for="name">Name Course</label>
            <br>
            {{form.name}}
            <br><br>
            {{form.class_id.label}}
            <br>
            {{form.class_id}}
            <br>
            <br>
            <button type="submit">Add</button>
        </form>
    </div>

</body>
<script>
    function myFunction() {
    var x = document.getElementById("myDIV");
    if (x.style.display === "block") {
        x.style.display = "none";
    } else {
        x.style.display = "block";
    }
    }
</script>
</html>

templates/main/det_attend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% if tcr_true %}
<body>
    <h3>{{object}}</h3>
    <p>Teacher</p>
    <ul>
        {% for attendance in list_attend %}
            <li>{{attendance}}</li>
        {% endfor %}
    </ul>
</body>
{% else %}
<body>
    <h3>{{object}}</h3>
    <p>Student</p>
    {{expired}}
    <div class="container">
        {% if form1 %}
            <form method="post">
                {% csrf_token %}
                {{form1}}
                <button type="submit">Post</button>
            </form>
        {% endif %}
    </div>
</body>
{% endif %}

</html>

templates/main/detail_crse.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        Haloo
    {% endblock title %}
    {% block link %}
    {% endblock link %}
</head>
<body>
    {% block content %}
        <p>{{tcr_true}}</p>
        <h2>Selamat Datang Di Mapel {{course}}</h2>
        <br><br>
        <p>List Absensi :</p>
        {% if tcr_true %}
            <ul>
                {% for attendancereq in attendance_req_list %}
                    <li>
                        <a href="{% url 'detail_attend' course.id attendancereq.id %}">{{attendancereq}}</a>
                        <form action="{% url 'remove-attendance' attendancereq.id %}" method="post">{% csrf_token %}<input type="submit" value="Delete"></form>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <ul>
                {% for attendancereq in attendance_req_list %}
                    <li>
                        {% if attendancereq.is_closed %}
                            <p>{{attendancereq}}</p>
                        {% else %}
                            <a href="{% url 'main:detail_attend' course.id attendancereq.id %}">{{attendancereq}}</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <p>List Materi:</p>
        <div class="section-course">
        {% for key, values in section_course.items %} <!-- inside section_course is a dictionary -->
            <div class="title-course d-flex justify-content-between px-2" >
                <div class="title-key d-flex flex-row" id="title-head">
                    <h2><a id="{{key}}" href="{% url 'subcourse:section_edit' key.pk %}">{{key}}</a></h2>
                    <!-- Button modal -->
                    <button type="button" class="btn btn-primary tcr-display" data-bs-toggle="modal" data-bs-target="#modal{{key.pk}}">
                        Edit Title
                    </button>
                    
                    <!-- Modal Title -->
                    <div class="modal fade" id="modal{{key.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3 class="modal-title bold" >Edit title</h3>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                            <form onsubmit="postPrevDefault('#title-form-{{key.pk}}',event)" class="title-form" id="title-form-{{key.pk}}">
                                {% csrf_token %}
                                <input type="hidden" name="pk" value="{{key.pk}}">
                                <input type="hidden" name="form-type" value="2">
                                <label for="title" class="text-dark">Title : </label>
                                {{form2.title}}
                                <a onclick="postPrevDefault('#title-form-{{key.pk}}',event)" class="btn btn-primary">Submit</a>
                            </form>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="btn-group dropstart tcr-display">
                    <button type="button" class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Create Activity
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item assignment" onclick="testFunction('{{key.pk}}','asgt',event)" data-bs-toggle="modal" data-bs-target="#activityModal">Assignment</a>
                        <a class="dropdown-item material" onclick="testFunction('{{key.pk}}','mtrl',event)" data-bs-toggle="modal" data-bs-target="#activityModal">Material</a>
                        <a class="dropdown-item sub-course" onclick="testFunction('{{key.pk}}','sbcs',event)" data-bs-toggle="modal" data-bs-target="#activityModal">Sub Course</a>
                        <a class="dropdown-item announcements" onclick="testFunction('{{key.pk}}','anct',event)" data-bs-toggle="modal" data-bs-target="#activityModal">Announcements</a>  
                    </div>
                </div>
            </div>
            <ul>
                {% for value in values %}
                    {% if value.name %}
                        <li><a href="{% url 'subcourse:sub_course' course.id value.get_slug%}">{{value}}</a></li>   
                    {% else %}
                        <li><a href="{% url 'subcourse:assignment' course.id value.get_slug%}">{{value}}</a></li>   
                    {% endif %}
                {% endfor %}
            </ul>
        {% endfor %}
        </div>
        <!-- Modal Activity -->
        <div class="modal fade" id="activityModal" tabindex="-1" aria-labelledby="activityModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="activityModalLabel">Add New Activity</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-dark" id="body-form">
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
            </div>
        </div>
        <br><br><br>
        <div class="tcr-display" style="min-height: 100px;margin-bottom: 100px;">
            <button id="btn1" class="btn btn-primary">Add New Section</button>
            <div id="myDIV1" class="add-section" style="margin: 10px 0; display: none;">
                <form method="post">
                    {% csrf_token %}
                    {{form2}}
                    <button type="submit">Add</button>         
                </form>
            </div>
            <br><br>
            <button id="btn2" class="btn btn-primary">Add New Attendance Req</button>
            <div id="myDIV2" style="display: none;">
                <form method="post">
                    {% csrf_token %}
                    {{form1.start_time.label}}
                    {{form1.start_time}}
                    <br>
                    {{form1.closed_time.label}}
                    {{form1.closed_time}}
                    <br>
                    {{form1.is_closed.label}}
                    {{form1.is_closed}}
                    <br>
                    <button type="submit">Add</button>         
                </form>
            </div>
        </div>
        {% endblock content %}
    </body>
{% block script %}
    <script type="text/javascript">
        var user_type = "{{user.user_type}}"
        if(user_type === "Std"){
            var x = document.querySelectorAll('.tcr-display')
            x.forEach(p => p.style.display = "none")
        }
        
        $(document).ready(function(){
            $("#btn1").click(function(){
                $("#myDIV1").toggle(100);
            });
            $("#btn2").click(function(){
                $("#myDIV2").toggle(100);
            });
        });

        var flat_conf = {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
        }

        $(".date-time").flatpickr(flat_conf)

        // every time form is submitted or button get clicked call this function
        function postPrevDefault(id,e){
            e.preventDefault();
            console.log('broo knp dah')
            var serializedata = $(id).serialize()
            $.ajax({
                type: 'POST',
                url: "{% url 'courses_page' course.pk %}",
                data: serializedata,
                success: function (response){
                    // close the form
                    $(".btn-close").trigger('click');
                    
                    $(".section-course").load(" .section-course");

                    $('.title-form').trigger('reset');
                },
                error: function (response) {
                    console.log('Jncuk')
                }
            })
        }

        function testFunction(pk,type,e){
            var form3 = (`
                <form id='form-sbcs-${pk}'>
                    {% csrf_token %}
                    <input type="hidden" name="form-type" value="3">
                    <input type="hidden" name="course_id" value="{{course.id}}">
                    <input type="hidden" name="sub_id" value="${pk}">
                    {{form3.name.label}}
                    {{form3.name}}<br>
                    {{form3.content1.label}}
                    {{form3.content1}}<br>
                    {{form3.content2.label}}
                    {{form3.content2}}<br>
                    <a onclick="postPrevDefault('#form-sbcs-${pk}',event)" class="btn btn-primary">Submit</a>
                </form>
                `)
            // ${pk} sama seperti 'The lazy {} {} over the {}'.format(var3, var2, var1)
            // BTW 'pk' ini adalah 'pk' nya subsection yaa
            var form4 = (
                `<form id='form-asgt-${pk}'>
                    {% csrf_token %}            
                    <input type="hidden" name="form-type" value="4">
                    <input type="hidden" name="course_id" value="{{course.id}}">
                    <input type="hidden" name="sub_id" value="${pk}">
                    {{form4.title.label}}
                    {{form4.title}}<br>
                    {{form4.description.label}}
                    {{form4.description}}<br>
                    {{form4.file.label}}
                    {{form4.file}}<br>
                    {{form4.start_time.label}}
                    {{form4.start_time}}<br>
                    {{form4.closed_time.label}}
                    {{form4.closed_time}}<br>
                    {{form4.is_closed.label}}
                    {{form4.is_closed}}<br>
                    <a onclick="postPrevDefault('#form-asgt-${pk}',event)" class="btn btn-primary">Submit</a>
                </form>`

            );
            if(type === 'sbcs'){
                $('#body-form').empty()
                $('#body-form').append(form3)
            }
            
            else if(type === 'asgt'){
                $('#body-form').empty()
                $('#body-form').append(form4)
                $(".date-time").flatpickr(flat_conf)

            }
            else{
                $('#body-form').empty()
            }
        }

    </script>
{% endblock script %}
</html>

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gabut</title>
</head>
<body>
    <p>{{user}}</p>
    <h4><a href="/">Back</a></h4>
    <ul>
    {% for course in courses %}
        <li><a href="{% url 'courses_page' course.id %}">{{course}}</a></li>
    {% endfor %}
    </ul>

    
    {% if tcr_or_not %}
        <a href="{% url 'add_course' %}">Add New</a>
    {% endif %}
        
</body>
</html>

templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h2>Hai Dunia</h2>
    <p><a href="/admin">Admin</a></p>
    <p><a href="{% url 'homey' %}">Home</a></p>
    <ul>
        <li><a href="{% url 'login' %}">Log In</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'logout' %}">Log Out</a></li>
    </ul>
</body>
</html>

templates/main/subcourse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hello Bro</p>
</body>
</html>